name = "qatar-stopover-ai-agent"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Production environment configuration
[env.production]
name = "qatar-stopover-ai-agent-production"
routes = [
  { pattern = "qatar-stopover.pages.dev/*", zone_name = "pages.dev" },
  { pattern = "your-custom-domain.com/*", zone_name = "your-custom-domain.com" }
]

# Production variables (secrets set via dashboard)
[env.production.vars]
ENVIRONMENT = "production"
NODE_ENV = "production"
DEFAULT_MODEL = "google/gemini-2.0-flash-exp"
FALLBACK_MODELS = "anthropic/claude-3-haiku,openai/gpt-4o-mini"
MAX_TOKENS = "4096"
TEMPERATURE = "0.7"
MAX_CONTEXT_MESSAGES = "15"
CONTEXT_WINDOW_TOKENS = "80000"
FUNCTION_CALLING_ENABLED = "true"
STREAMING_ENABLED = "true"
RATE_LIMIT_REQUESTS_PER_MINUTE = "60"
RATE_LIMIT_REQUESTS_PER_HOUR = "1000"
RATE_LIMIT_BURST_SIZE = "10"
ANALYTICS_ENABLED = "true"
PERFORMANCE_MONITORING_ENABLED = "true"
ERROR_REPORTING_ENABLED = "true"
LOG_LEVEL = "info"
LOG_FORMAT = "json"
ENABLE_REQUEST_LOGGING = "true"
ENABLE_ERROR_LOGGING = "true"
ENABLE_PERFORMANCE_LOGGING = "true"
CORS_ORIGINS = "https://qatar-stopover-ai-agent.pages.dev,https://your-custom-domain.com"
CSRF_PROTECTION_ENABLED = "true"
SECURITY_HEADERS_ENABLED = "true"
CACHE_TTL_STATIC_ASSETS = "31536000"
CACHE_TTL_API_RESPONSES = "300"
CACHE_TTL_LLM_RESPONSES = "0"
CDN_ENABLED = "true"
COMPRESSION_ENABLED = "true"
MINIFICATION_ENABLED = "true"
IMAGE_OPTIMIZATION_ENABLED = "true"
LAZY_LOADING_ENABLED = "true"
FEATURE_VOICE_INPUT = "false"
FEATURE_ADVANCED_ANALYTICS = "true"
FEATURE_A_B_TESTING = "false"
FEATURE_DEBUG_MODE = "false"

# Staging environment configuration
[env.staging]
name = "qatar-stopover-ai-agent-staging"
routes = [
  { pattern = "qatar-stopover-staging.pages.dev/*", zone_name = "pages.dev" }
]

# Staging variables
[env.staging.vars]
ENVIRONMENT = "staging"
NODE_ENV = "staging"
DEFAULT_MODEL = "google/gemini-2.0-flash-exp"
FALLBACK_MODELS = "anthropic/claude-3-haiku,openai/gpt-4o-mini"
MAX_TOKENS = "4096"
TEMPERATURE = "0.7"
MAX_CONTEXT_MESSAGES = "20"
CONTEXT_WINDOW_TOKENS = "100000"
FUNCTION_CALLING_ENABLED = "true"
STREAMING_ENABLED = "true"
RATE_LIMIT_REQUESTS_PER_MINUTE = "120"
RATE_LIMIT_REQUESTS_PER_HOUR = "2000"
RATE_LIMIT_BURST_SIZE = "20"
ANALYTICS_ENABLED = "true"
PERFORMANCE_MONITORING_ENABLED = "true"
ERROR_REPORTING_ENABLED = "true"
LOG_LEVEL = "debug"
LOG_FORMAT = "json"
ENABLE_REQUEST_LOGGING = "true"
ENABLE_ERROR_LOGGING = "true"
ENABLE_PERFORMANCE_LOGGING = "true"
ENABLE_DEBUG_LOGGING = "true"
CORS_ORIGINS = "https://qatar-stopover-ai-agent-staging.pages.dev,https://staging.your-domain.com"
CSRF_PROTECTION_ENABLED = "true"
SECURITY_HEADERS_ENABLED = "true"
CACHE_TTL_STATIC_ASSETS = "3600"
CACHE_TTL_API_RESPONSES = "60"
CACHE_TTL_LLM_RESPONSES = "0"
CDN_ENABLED = "true"
COMPRESSION_ENABLED = "true"
MINIFICATION_ENABLED = "false"
IMAGE_OPTIMIZATION_ENABLED = "true"
LAZY_LOADING_ENABLED = "true"
FEATURE_VOICE_INPUT = "true"
FEATURE_ADVANCED_ANALYTICS = "true"
FEATURE_A_B_TESTING = "true"
FEATURE_DEBUG_MODE = "true"

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

# KV Namespaces for configuration and cached data
[[kv_namespaces]]
binding = "QATAR_STOPOVER_KV"
id = "placeholder_kv_id"
preview_id = "placeholder_kv_preview_id"

# R2 Buckets for images and static assets
[[r2_buckets]]
binding = "QATAR_STOPOVER_ASSETS"
bucket_name = "qatar-stopover-assets"

# Durable Objects for conversation state management
[[durable_objects.bindings]]
name = "CONVERSATION_STATE"
class_name = "ConversationState"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_classes = ["ConversationState"]