name = "qatar-stopover-ai-agent"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "qatar-stopover-ai-agent-production"

[env.staging]
name = "qatar-stopover-ai-agent-staging"

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

# Environment variables (will be set in Cloudflare dashboard)
# [vars]
# ENVIRONMENT = "development"